### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ghost** [evilpenguin/ThatWebInspector#1]
Where?

**Comment by evilpenguin** [comment]
What?

**Comment by ghost** [comment]
Releases must be here https://github.com/evilpenguin/ThatWebInspector/releases
Not in project files

**Comment by evilpenguin** [comment]
https://github.com/evilpenguin/ThatWebInspector/blob/main/packages/com.evilpenguin.thatwebinspector_0.1-1%2Bdebug_iphoneos-arm.deb

**Comment by ghost** [comment]
> https://github.com/evilpenguin/ThatWebInspector/blob/main/packages/com.evilpenguin.thatwebinspector_0.1-1%2Bdebug_iphoneos-arm.deb

Releases must be here https://github.com/evilpenguin/ThatWebInspector/releases
Not inside packages folder

**Comment by evilpenguin** [comment]
I only add the `packages` folder for convenience. Feel free to compile and use it.

**Comment by ghost** [comment]
Maybe you don't understand english well

**Comment by ghost** [comment]
> I only add the `packages` folder for convenience. Feel free to compile and use it.

All produced/built files must be in releases tab, not inside your code

**Comment by ghost** [comment]
AHAHAHAH I found that you do the same in all your projects

**Comment by evilpenguin** [comment]
I know how `git` and `github` work, tyvm.

**Comment by ghost** [comment]
Ok 👌

**Comment by evilpenguin** [comment]
> AHAHAHAH I found that you do the same in all your projects

Correct, all my stuff is like this. I'm too lazy to build a release in `github` so you get the `packages` folder that is generated from Theos when ya know, you run `make package` :)

**Comment by evilpenguin** [comment]
> > AHAHAHAH I found that you do the same in all your projects
> 
> Correct, all my stuff is like this.

Like I said, its simply for convenience - im going to to build a release. Just pushing code.

**Comment by ghost** [comment]
*RELEASES TAB*: "am i joke to you?"

**Comment by evilpenguin** [comment]
Yes....
